title: Shiyao Meng
description: trying to solve interesting problems
baseurl: "shiyao.me"
url: "https://eaziym.github.io/shiyao.me"
repository: eaziym/shiyao.me
github_username: eaziym
linkedin_username: shiyao-meng

collections:
  projects:
    output: true
    permalink: /projects/:title/
    sort_by: date

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

author:
  name: Shiyao Meng
  email: e0773600@u.nus.edu
  linkedin: https://www.linkedin.com/in/shiyao-meng/

# Add after existing content
minimal:
  social_links:
    linkedin: shiyao-meng
    github: eaziym
  navigation:
    - title: Projects
      url: /shiyao.me/projects
    - title: GitHub
      url: https://github.com/eaziym
